In [8]:
import numpy as np
import random as rng
import math as mt

class atom:
    def __init__(self,a,b):
        self.x=a
        self.y=b
        self.dx=0
        self.dy=0

class systm:
    def __init__(self, mm):
        self.dimension = mm
        self.atoms = []
        self.number_of_atoms = 0
        self.occupied_places = np.zeros((mm, mm))
        
    def add_atom(self):
        while(True):
            t1=int(rng.random()*(self.dimension-1))
            t2=int(rng.random()*(self.dimension-1))
            if(self.occupied_places[t1][t2] == 0):
                self.atoms.append(atom(t2, t1))
                self.occupied_places[t1][t2] = 1
                self.number_of_atoms += 1
                break
        
    def move_sys(self):
        for i in range(self.number_of_atoms):
            t = int(rng.random()*4)
            print(t)
            if(t == 0 and self.atoms[i].x < self.dimension - 1):
                if(self.occupied_places[self.atoms[i].y][self.atoms[i].x+1] == 0):
                    self.occupied_places[self.atoms[i].y][self.atoms[i].x] = 0
                    self.occupied_places[self.atoms[i].y][self.atoms[i].x+1] = 1
                    self.atoms[i].x += 1
                    self.atoms[i].dx += 1
                    
            elif(t == 0 and self.atoms[i].x == self.dimension - 1):
                if(self.occupied_places[self.atoms[i].y][0] == 0):
                    self.occupied_places[self.atoms[i].y][self.atoms[i].x] = 0
                    self.occupied_places[self.atoms[i].y][0] = 1
                    self.atoms[i].x = 0
                    self.atoms[i].dx += 1
                    
            elif(t == 1 and self.atoms[i].x > 0):
                if(self.occupied_places[self.atoms[i].y][self.atoms[i].x - 1] == 0):
                    self.occupied_places[self.atoms[i].y][self.atoms[i].x] = 0
                    self.occupied_places[self.atoms[i].y][self.atoms[i].x - 1] = 1
                    self.atoms[i].x -= 1
                    self.atoms[i].dx -= 1
            
            elif(t == 1 and self.atoms[i].x == 0):
                if(self.occupied_places[self.atoms[i].y][self.dimension - 1] == 0):
                    self.occupied_places[self.atoms[i].y][self.atoms[i].x] = 0
                    self.occupied_places[self.atoms[i].y][self.dimension - 1] = 1
                    self.atoms[i].x = self.dimension - 1
                    self.atoms[i].dx -= 1
                    
            elif(t == 2 and self.atoms[i].y > 0):
                if(self.occupied_places[self.atoms[i].y - 1][self.atoms[i].x] == 0):
                    self.occupied_places[self.atoms[i].y][self.atoms[i].x] = 0
                    self.occupied_places[self.atoms[i].y - 1][self.atoms[i].x] = 1
                    self.atoms[i].y -= 1
                    self.atoms[i].dy += 1
                    
            elif(t == 2 and self.atoms[i].y == 0):
                if(self.occupied_places[self.dimension - 1][self.atoms[i].x] == 0):
                    self.occupied_places[self.atoms[i].y][self.atoms[i].x] = 0
                    self.occupied_places[self.dimension - 1][self.atoms[i].x] = 1
                    self.atoms[i].y = self.dimension - 1
                    self.atoms[i].dy += 1
                    
            elif(t == 3 and self.atoms[i].y < self.dimension - 1):
                if(self.occupied_places[self.atoms[i].y + 1][self.atoms[i].x] == 0):
                    self.occupied_places[self.atoms[i].y][self.atoms[i].x] = 0
                    self.occupied_places[self.atoms[i].y + 1][self.atoms[i].x] = 1
                    self.atoms[i].y += 1
                    self.atoms[i].dy -= 1
                    
            elif(t == 3 and self.atoms[i].y == self.dimension - 1):
                if(self.occupied_places[0][self.atoms[i].x] == 0):
                    self.occupied_places[self.atoms[i].y][self.atoms[i].x] = 0
                    self.occupied_places[0][self.atoms[i].x] = 1
                    self.atoms[i].y = 0
                    self.atoms[i].dy -= 1
    def print_sys(self):
        print(self.occupied_places)
    
    def return_r():
        r = []
        for(i in self.number_of_atoms):
            r.append(mt.sqrt(self.atoms[i].dx**2 + self.atoms[i].dy**2))
            
        return()
            

In [10]:
# Create independent systems
L = 20
N_MCS = 50
MCS = range(N_MCS)
indep_real = []
for i in 
#Fill systems with atoms
for i in range(8):
    dif_2D.add_atom()
#Calculate mean difusion coeficient





print sys:
[[1. 0. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [0. 0. 0. 0.]]
first atom:
0
2
move:
3
2
1
3
1
2
0
1
first atom:
0
3
print sys:
[[0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [1. 0. 1. 0.]
 [1. 0. 0. 0.]]
move:
1
2
2
0
3
0
2
1
first atom:
3
3
print sys:
[[0. 0. 0. 1.]
 [1. 0. 1. 1.]
 [0. 0. 0. 1.]
 [0. 1. 1. 1.]]
